//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiTienda.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clientes()
        {
            this.datosEnvio = new HashSet<datosEnvio>();
            this.metodoPago = new HashSet<metodoPago>();
            this.ordenCliente = new HashSet<ordenCliente>();
        }
    
        public int Id_cliente { get; set; }
        [Display(Name = "Nombre")]
        public string nombre { get; set; }
        [Display(Name = "Apellido paterno")]
        public string apellido_p { get; set; }
        [Display(Name = "Apellido materno")]
        public string apellido_m { get; set; }
        public string correo { get; set; }
        public string contraseña { get; set; }
        [Display(Name = "Fecha de nacimiento")]
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string rfc { get; set; }
        public Nullable<int> telefono { get; set; }
        public string rol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<datosEnvio> datosEnvio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<metodoPago> metodoPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordenCliente> ordenCliente { get; set; }
    }
}
