//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiTienda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class datosEnvio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public datosEnvio()
        {
            this.ordenCliente = new HashSet<ordenCliente>();
        }
    
        public int Id_datosEnvio { get; set; }
        public string calle { get; set; }
        public string colonia { get; set; }
        public string estado { get; set; }
        public string municipio { get; set; }
        public string num_exterior { get; set; }
        public string num_interior { get; set; }
        public string cp { get; set; }
        public Nullable<int> telefono { get; set; }
        public int id_usuario { get; set; }
    
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordenCliente> ordenCliente { get; set; }
    }
}
