//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiTienda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordenProducto
    {
        public int Id_ordenCliente { get; set; }
        public int id_producto { get; set; }
        public Nullable<double> cantidad { get; set; }
    
        public virtual ordenCliente ordenCliente { get; set; }
        public virtual productos productos { get; set; }
    }
}
