//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiTienda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordenCliente
    {
        public int Id_ordenCliente { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> num_confirmacion { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<int> num_guia { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public int id_usuario { get; set; }
        public int id_datosEnvio { get; set; }
        public int id_paqueteria { get; set; }
    
        public virtual datosEnvio datosEnvio { get; set; }
        public virtual paqueterias paqueterias { get; set; }
        public virtual usuarios usuarios { get; set; }
        public virtual ordenProducto ordenProducto { get; set; }
    }
}
