//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiTienda.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosEnvios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatosEnvios()
        {
            this.OrdenCliente = new HashSet<OrdenCliente>();
        }
    
        public int Id { get; set; }
        public string calle { get; set; }
        public string colonia { get; set; }
        public string estado { get; set; }
        public string municipio { get; set; }
        public Nullable<int> num_ext { get; set; }
        public Nullable<int> num_int { get; set; }
        public Nullable<int> cp { get; set; }
        public Nullable<int> telefono { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenCliente> OrdenCliente { get; set; }
    }
}
