//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiTienda.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenProducto
    {
        public int Id { get; set; }
        public Nullable<int> id_producto { get; set; }
        public string cantida { get; set; }
        public Nullable<int> id_OrdenCliente { get; set; }
    
        public virtual OrdenCliente OrdenCliente { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
