//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiTienda.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenCliente()
        {
            this.OrdenProducto = new HashSet<OrdenProducto>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string num_confirmacion { get; set; }
        public string total { get; set; }
        public string num_guia { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public Nullable<int> id_datoEnvio { get; set; }
        public Nullable<int> id_paqueteria { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual DatosEnvios DatosEnvios { get; set; }
        public virtual Paqueterias Paqueterias { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenProducto> OrdenProducto { get; set; }
    }
}
