//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiTienda.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paqueterias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paqueterias()
        {
            this.OrdenCliente = new HashSet<OrdenCliente>();
        }
    
        public int Id { get; set; }
        public string nombre { get; set; }
        public string rfc { get; set; }
        public Nullable<int> telefono { get; set; }
        public string web { get; set; }
        public string direccion { get; set; }
        public string contacto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenCliente> OrdenCliente { get; set; }
    }
}
